apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teste-argo-canary-deploy
  namespace: argocd
spec:
  project: gitops3

  source:
    repoURL: 'https://github.com/robsonsantosdevops/gitopspublic.git'
    targetRevision: HEAD
    path: canary
  destination: 
    server: https://kubernetes.default.svc
    namespace: teste3

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
# this manually creates the default project
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops3
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'