# # apiVersion: argoproj.io/v1alpha1
# # kind: Rollout
# # metadata:
# #   name: teste-argo-canary
# #   namespace: argocd
# # spec:
# #   targetSize: 50%
# #   selector:
# #     matchLabels:
# #       app: teste-argo-canary
# #   template:
# #     metadata:
# #       labels:
# #         app: teste-argo-canary
# #     spec:
# #       containers:
# #       - name: nginx
# #         image: nginx:1.19.0
# #         ports:
# #         - containerPort: 80
# #         readinessProbe:
# #           httpGet:
# #             path: /
# #             port: 80
# #         livenessProbe:
# #           httpGet:
# #             path: /
# #             port: 80
# #       replicas: 1
# #       annotations:
# #         argocd.argoproj.io/sync-wave: "10"
# #         argocd.argoproj.io/sync-options: SkipDryRun=true

# #   strategy:
# #     canary:
# #       steps:
# #       - setWeight: 10
# #         pause:
# #           duration: 5m
# #       - setWeight: 20
# #         pause:
# #           duration: 5m
# #       - setWeight: 30
# #         pause:
# #           duration: 5m
# #       - setWeight: 40
# #         pause:
# #           duration: 5m
# #       - setWeight: 50
# #         pause:
# #           duration: 5m
# #       - setWeight: 100
# #     maxSurge: 1
# #     maxUnavailable: 0
# #     type: RollingUpdate
# #   source:
# #     applicationSource:
# #       repoURL: 'https://github.com/robsonsantosdevops/gitopspublic.git'
# #       path: dev2
# #       targetRevision: HEAD
# #       helm:
# #         releaseName: teste-argo-canary
# #       directory:
# #         recurse: true
# #       plugin:
# #         name: helm
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
# metadata:
#   name: teste-argo-canary-rollout
# spec:
#   replicas: 10
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.15.4
#         ports:
#         - containerPort: 80
#   minReadySeconds: 30
#   revisionHistoryLimit: 3
#   strategy:
#     canary: #Indicates that the rollout should use the Canary strategy
#       maxSurge: "25%"
#       maxUnavailable: 0
#       steps:
#       - setWeight: 10
#       - pause:
#           duration: 1h # 1 hour
#       - setWeight: 20
#       - pause: {} # pause indefinitely
# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
# metadata:
#   name: site-estatico-rollout
#   namespace: teste2
# spec:
#   replicas: 10
#   strategy:
#     canary:
#       steps:
#       - setWeight: 20
#       - pause: {duration: 10}
#       - setWeight: 40
#       - pause: {duration: 10}
#       - setWeight: 60
#       - pause: {duration: 10}
#       - setWeight: 80
#       - pause: {duration: 10}
#       - setWeight: 100    
#   revisionHistoryLimit: 2
#   selector:
#     matchLabels:
#       app: site-estatico
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-deployment
  namespace: teste2
spec:
  replicas: 10
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30}
      - setWeight: 50
      - pause: {duration: 60}
      - setWeight: 80
      - pause: {}
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
# metadata:
#   name: chip
#   namespace: chip
# spec:
#   replicas: 10
#   strategy:
#     canary:
#       steps:
#       - setWeight: 20
#       - pause: {duration: 10}
#       - setWeight: 40
#       - pause: {duration: 10}
#       - setWeight: 60
#       - pause: {duration: 10}
#       - setWeight: 80
#       - pause: {duration: 10}
#       - setWeight: 100    
#   revisionHistoryLimit: 2
#   selector:
#     matchLabels:
#       app: chip