apiVersion: v1
kind: ConfigMap
metadata:
  name: canary-html
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Canary Deployment</title>
    </head>
    <body>
    <h1>Canary Deployment</h1>
    <p>This is the canary deployment.</p>
    </body>
    </html>
